### ISSUE TITLE
pod/capm3-ironic-* ironic-api failing waiting for eth2 int

### ISSUE THREAD

**Issue by FruityWelsh** [metal3-io/baremetal-operator#1043]
Deployed running 
```
## Installed deps:
sudo yum install httpd-tools go
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
sudo mv kustomize /usr/bin/kustomize 
## Main install
git clone https://github.com/metal3-io/baremetal-operator.git
cd baremetal-operator
sudo IRONIC_HOST=my-ironic-host IRONIC_HOST_IP=<availble ip in my subnet> KUBECONFIG="/etc/rancher/rke2/rke2.yaml" tools/deploy.sh deploy-BMO true deploy-Ironic true deploy-Keepalived true
```

This falls in to a loopbackoff with the logs of the ironic-api container in the pod giving the error:
```
Waiting for eth2 interface to be configured
Device "eth2" does not exist.
```

Host machine info:
```
RHEL 8.5
RKE2 kubernetes
```
Network devices:
```
eno1np0
eno2np1 
eno3 
eno4
```
All of which are teamed into a singular connection using networkmanager.

**Comment by zhouhao3** [comment]
It seems that you need to set environment variables according to your actual network environment.

**Comment by Rozzii** [comment]
/triage accepted
/lifecycle stale
If the answer was sufficient please @FruityWelsh close the ticket.

**Comment by nitendra-thakur** [comment]
@FruityWelsh How dod you resolve this? I'm hitting the same issue. Which environment variable is to be set to control this behavior of ironic?
None of [these](https://github.com/metal3-io/baremetal-operator/blob/main/docs/deploying.md#deployment-commands) looks to be the one.

I'm trying to deploy ironic on the management clutser and is stuck due to this issue at the last step of 
[deploying-the-metal3-provider](https://github.com/metal3-io/cluster-api-provider-metal3/#deploying-the-metal3-provider)

**Comment by furkatgofurov7** [comment]
> @FruityWelsh How dod you resolve this? I'm hitting the same issue. Which environment variable is to be set to control this behavior of ironic? None of [these](https://github.com/metal3-io/baremetal-operator/blob/main/docs/deploying.md#deployment-commands) looks to be the one.

@FruityWelsh it is [PROVISIONING_INTERFACE](https://github.com/metal3-io/baremetal-operator/blob/main/config/default/ironic.env#L2). Please check "Important Note" part of the document: https://github.com/metal3-io/baremetal-operator/blob/main/docs/deploying.md#useful-tips
