### ISSUE TITLE
Failed to delete BMH 

### ISSUE THREAD

**Issue by k82cn** [metal3-io/baremetal-operator#1163]
When failed to create metadata because of network, I'd like to delete the whole namespace to re-create the cluster from scratch; all other CRs are deleted, e.g. Metal3Cluster. But BareMetalHost can not be delete, and the status of namespace keep Terminating forever; and `kubectl delete bmh --force` also does not work.

Here's the log from baremetal-operator pod:

```
{"level":"info","ts":1661847763.8791144,"logger":"controllers.BareMetalHost","msg":"start","baremetalhost":"my-example/my-host"}
{"level":"info","ts":1661847763.8791723,"logger":"controllers.BareMetalHost","msg":"hardwareData is ready to be deleted","baremetalhost":"my-example/my-host"}
{"level":"info","ts":1661847763.8933568,"logger":"controllers.BareMetalHost","msg":"provisioner is not ready","baremetalhost":"my-example/my-host","RequeueAfter:":30}
```

**Comment by Rozzii** [comment]
@k82cn 
As I see from the information that you have provided the BMH was either not provisioned correctly or can't talk to ironic deployment or the ironic-deployment is deleted. As far as I know when BMH is deleted it triggers  deprovisioning by default and it seems in your case the deprovisioning fails for one or more of the aforementioned reasons. 

As a workaround I would suggest using the "detached" annotation as described in the user-guide https://metal3io.netlify.app/bmo/detached_annotation.html

**Comment by ReggieCarey** [comment]
I've experienced this in the past. BMH does not go away after being deleted because the finalizer won't release it.  Apparently a functioning IRONIC deployment is necessary to let the finalizer proceed to removing the BMH and it can take 30 minutes to go away.

You can force remove the BMH by editing the deployed resource and removing the finalizer.  This is NOT recommended as it can leave other resources in an odd state.  I call it a last ditch effort.

**Comment by Rozzii** [comment]
@k82cn can we close this issue ?
