### ISSUE TITLE
Allow not using ironic-inspect at all

### ISSUE THREAD

**Issue by ydp** [metal3-io/baremetal-operator#1229]
**User Story**

As a [developer/user/operator] I would like to not use inspection function at all, because I would like to provide hardware detail on our own, and not even install ironic-inspector.

**Detailed Description**

To avoid install ironic-inspector when it's not necessary.

**Anything else you would like to add:**

Did not find this is possible, could anyone help answer whether this is valuable for someone else?

/kind feature

**Comment by dtantsur** [comment]
It's possible to disable inspection via an annotation. Is it what you're looking for?

**Comment by ydp** [comment]
Hi @dtantsur  Thank you for reply! I saw that annotation, but disabling it looks like will fail cluster provision, right? I did not create a cluster successfully when disable inspector, because the Metal3machine will check whether there is a baremetalhost that has the required NIC in the hardware detail (oh, when I wrote this, I just realized that I should probably try provide the NIC in hardware detail annotation...). 
I also realized that this feature request is not realistic, because even if baremetal-operator does not use it, IPA still needs it to get the node UUID when starting, otherwise IPA will fail to look up node? 

I ask this is because when I saw tinkerbell, which is another bare metal provision project, it does not have this inspection module, so I am wonder if we can use Ironic without inspector, because if I uses Ironic in my data center, I would know all the hardware detail when purchasing, I can just provide it explicitly, no need to automatically inspect it, as when scale becomes large, the inspector might be a bottleneck, from my understanding, it maintains an internal state machine and some data in memory to complete the inspection process.

**Comment by furkatgofurov7** [comment]
/cc @Rozzii 

Please take a look and provide an explanation.

**Comment by dtantsur** [comment]
@ydp 

It's definitely possible to use Metal3 without inspection since that's what one of our projects (in OpenShift) does. You may need to provide just enough information to make subsequent steps work. Outside of Metal3, a lot of people use Ironic without Inspector. (As an aside, I'm driving the effort to merge Inspector into Ironic.)

IPA does not rely on inspection, it's fine if you provide bootMACAddress for all hosts.

The only thing I'm not sure about is whether BMO expects Inspector to be present even if unused. This may be something that needs fixing.

**Comment by ydp** [comment]
Hi @dtantsur Thank you for explaining!

May I know why merge Inspector into Ironic? Based on https://specs.openstack.org/openstack/ironic-inspector-specs/specs/HA_inspector.html, will that affect the number of node Ironic managing? As I try to run Ironic in a large scale, maybe several hundreds of nodes.

I thought that IPA will use this API https://docs.openstack.org/api-ref/baremetal-introspection/?expanded=#ramdisk-callback to get the node UUID upon startup, then doing lookup later with UUID via this API https://docs.openstack.org/api-ref/baremetal/?expanded=agent-lookup-detail#agent-lookup , so we can configure IPA somehow to not execute like this sequence? 

https://github.com/metal3-io/baremetal-operator/blob/main/pkg/provisioner/ironic/ironic.go#L1935 this is where BMO throws error when Inspector endpoint is not ready.

**Comment by dtantsur** [comment]
> May I know why merge Inspector into Ironic?

Having it as a separate service is a historical artefact that has no meaning nowadays.

> Based on https://specs.openstack.org/openstack/ironic-inspector-specs/specs/HA_inspector.html, will that affect the number of node Ironic managing?

This is one of the aspects I hope to significantly *improve* by the merge. Ironic has a good HA story, in Inspector it was an afterthought. By reusing the Ironic HA bits, in-band inspection can be made much more scalable.

In any case, if you don't use it, you don't care.

> I thought that IPA will use this API https://docs.openstack.org/api-ref/baremetal-introspection/?expanded=#ramdisk-callback to get the node UUID upon startup, then doing lookup later with UUID via this API https://docs.openstack.org/api-ref/baremetal/?expanded=agent-lookup-detail#agent-lookup

This is a possible scenario, but it does not work like this now. Currently, inspector callback and ironic lookup are completely independent. Furthermore, inspection only happens if you provide the inspector callback URL to the agent (our ironic-image does it).

> https://github.com/metal3-io/baremetal-operator/blob/main/pkg/provisioner/ironic/ironic.go#L1935 this is where BMO throws error when Inspector endpoint is not ready.

Aha, this is exactly what I thought: BMO requires ironic-inspector, regardless of whether it's needed. Because BMO does not know if you're going to use inspection for any of the hosts. This is fixable if you have cycles to work on a change. (This problem will also go away with the merge, but it's going to take time.)

**Comment by ydp** [comment]
@dtantsur Thank you so much for the detailed explanation! Look forward to the merging work you're doing!
I will try first whether I can remove the dependency in my local first.

**Comment by Rozzii** [comment]
Hi, @ydp has @dtantsur answered your question completely? Can we close this issue ?

**Comment by dtantsur** [comment]
I think this is a valid enhancement request. It will be rendered obsolete when we merge inspector into ironic, but that will take time. Meanwhile, if someone wants to make handling of missing Inspector more graceful, I'd be happy to review the patch.

/triage accepted
/kind feature
/help

**Comment by ydp** [comment]
Hi @dtantsur  I had a test today, it turns out that setting `IRONIC_INSPECTOR_ENDPOINT` is required to successfully to start the baremetal operator, otherwise it exits at https://github.com/metal3-io/baremetal-operator/blob/main/pkg/provisioner/ironic/factory.go#L60 .
What I failed in my previous case is that I set this variable, but shutdown the inspector endpoint, then it failed at the check inspector ready code. 
So my understanding current code is working as intended, unless we want a design change. like somehow allow user not setting inspector endpoint when starting baremetal operator, then skip the endpoint check later, but this would change current behavior.
Do you prefer to keep current behavior or allowing empty inspector endpoint? If first, we can just close the issue, if later, I can try working on it.
