### ISSUE TITLE
Question: From new CNCF Contributor

### ISSUE THREAD

**Issue by danielkurniadi** [metal3-io/baremetal-operator#1395]
Hi team. I'm a (senior) software engineer with 4 years of experience in both big tech (TikTok) and startup (Gojek, Zendesk, Arta Finance).

I want to get up-to speed to help this project take off. However, I need more context so that my time and contribution can be maximal without giving spamming the main contributors here too much in my early ramp-up stage.

### Resources to Learn
Gathering from what I found. Please add more if you find anything useful to read

- [Slack](https://kubernetes.slack.com/?redir=%2Fmessages%2FCHD49TLE7) (#cluster-api-baremetal channel)
- [Documentation](https://book.metal3.io/) (books and tutorial)
- [Youtube](https://www.youtube.com/channel/UC_xneeYbo-Dl4g-U78xW15g/videos) channel
   * [Deep dive Video](https://www.youtube.com/watch?v=VFbIHc3NbJo&list=PL2h5ikWC8viKmhbXHo1epPelGdCkVlF16&pp=iAQB)
- [Github](https://github.com/metal3-io/baremetal-operator) (this code base)

ETA: 1-2 weeks of tutorials to ramp up.

### Project Cycle, Sprint and Milestones

I'm yet to find any other than Github issues but perhaps I can start there. If we happen to have external platform for managing sprints / feature roadmap, can someone in here help point out so that I can align with the direction of the team? Reason I asked is because:
- I want to try pick easier task in my 1st few weeks.
- Once I get advanced, I want to try having a more vertical or end-end responsibility for one or two specific features.
- I want to make sure that when the team give me the task, I can complete it within the expected time so that people effort is not wasted and I don't create blockers.
- Link or invite to sprint ticket platform will be nice to facilitate communication and progress update.

Will be great to know the challenge in this roadmap.

### Mentor or Maintainers 

Good to have someone in contact that is either part-time or full-time working on this project.

### Commitment

I will have 20-30 hours per week to commit to this project by early November - December 2023. I probably have more bandwidth in 2024 Q1-Q2. I'm also interested in exploring bare-metal clouds for enterprise solution for my own company.

**Comment by danielkurniadi** [comment]
If you want to book meeting with me:
- https://calendly.com/dkurniadi-daniel/open-source-1-1

**Comment by lentzi90** [comment]
/triage accepted
Thanks for reaching out! We definitely need to get better at helping new contributors and setting clear goals or define the roadmap.

From my perspective, we have 2 main projects going on at the moment.

1. Implementing the [v1beta1 API version](https://github.com/metal3-io/metal3-docs/blob/main/design/baremetal-operator/bmh-v1beta1.md) for the Baremetal Operator.
2. Implementing e2e test for the Baremetal Operator: https://github.com/orgs/metal3-io/projects/5

I'm not sure how suitable they are for first time contributors though. Probably the e2e tests should be quite alright, and I can also help mentoring in this area.

Let's see if we can get some more `good-first-issue` suggestions from others!
@Rozzii @dtantsur what do you think?

**Comment by Rozzii** [comment]
Hi and welcome!

It would be great to have someone with you're experience be a regular contributor on the project!

Please feel free to join the weekly community meetings to keep in touch with us.
Community Meeting: https://zoom.us/j/97255696401?pwd=ZlJMckNFLzdxMDNZN2xvTW5oa2lCZz09
See the minutes of meeting document also: https://docs.google.com/document/d/1IkEIh-ffWY3DaNX3aFcAxGbttdEY_symo7WAGmzkWhU/edit#heading=h.1dwq09frngr6

Just to extend on @lentzi90 's answer a bit:

Using this query you can find all currently open issues in the organization and where you see "good first issue" those are the issues that would be good for someone who is just starting with the project.
There are also issues tagged with the "help wanted" label so feel free to check those too and also the issues that have "lifecycle frozen" those are on our "wish list" (mostly feature ideas).
General Issue list: https://github.com/issues?q=archived%3Afalse+user%3Ametal3-io++is%3Aopen+ 
Help wanted: https://github.com/issues?q=archived%3Afalse+user%3Ametal3-io+label%3A%22help+wanted%22+is%3Aissue+sort%3Acreated-asc+is%3Aopen+
Frozen: https://github.com/issues?q=archived%3Afalse+user%3Ametal3-io+label%3Alifecycle%2Ffrozen+is%3Aissue+sort%3Acreated-asc+is%3Aopen+

You can find the maintainers and reviewers of the given repo under the root dir in the OWNERS file ("approvers" are the folks who have the most experience)

Related to sprints and such:
cluster-api-metal3 follow the release cycle of the [cluster-api](https://github.com/kubernetes-sigs/cluster-api) project while bare-metal-operator and other repositories have their own release cycles. Because some part of the project follow
the release cycle of other projects it is a bit complicated to have pre-release milestones and we have not yet discussed about the state of our public task management in detail with the community.

I agree that we should make transparent issue tracking process for the community but this is a TODO at the moment , but thanks for mentioning this we have to do something about this soon.

**Comment by danielkurniadi** [comment]
This is awesome. Thanks @lentzi90 @Rozzii  I'll continue my learning on metal3-io in the next 2 weeks and come back here to pick up one of the [open issues with help wanted but no assignees](archived:false user:metal3-io label:"help wanted" is:issue sort:created-asc is:open no:assignee).

Also I wonder if you have tips how to test or verify that your changes are working, other than unit tests. From my pov, metal3-io has quite number of components so I wonder how should I verify:
1. The current component that I modify is working fine in isolation after some changes
2. The current component that I modify is working fine and its integration with other components works too.
3. Testing end-end manually using small workload / cluster.

In the meantime, I'm trying to understand the hack script in [testing docs](https://github.com/metal3-io/baremetal-operator/blob/main/docs/testing.md).

**Comment by lentzi90** [comment]
I would say that in general, it would be enough to test your changes with [make test](https://github.com/metal3-io/baremetal-operator/blob/7247b4237f213396293bb5d391b2e7dafa8e63c5/Makefile#L83-L85) (or other relevant make targets). If you have issues with the make targets, then the hack scripts can help since they provide a way to run the tests in the same way as we do for CI. In general this should not be needed though.

For integration/end to end, take a look at [metal3-dev-env](https://github.com/metal3-io/metal3-dev-env) and perhaps also the brand new [BMO e2e tests](https://github.com/metal3-io/baremetal-operator/tree/main/test/e2e) (work in progress).
The current state is that BMO is tested using metal3-dev-env, which tests [CAPM3](https://github.com/metal3-io/cluster-api-provider-metal3) together with BMO. This is mainly exercising CAPM3 though, but since it builds on BMO, BMO is of course also tested.
