### ISSUE TITLE
Provisioning a bare metal server using UEFI mode fails 

### ISSUE THREAD

**Issue by emailallau** [metal3-io/baremetal-operator#1545]
While deploying bare metal servers using UEFI mode, the observation is, it fails in provisioning step with below error 

 errorMessage: |-
	Image provisioning failed: Deploy step deploy.prepare_instance_boot failed: Failed to install a bootloader when deploying node 765b0135-57b5-47c3-8a49-a2bf783131d0: Unexpected error while running command.
	Command: sgdisk -i 2 /dev/nvme0n1
	Exit code: 2
	Stdout: ''
	Stderr: 'Invalid partition data!\n'
  errorType: provisioning error

I have observed this error on two different bare metal servers, has anyone else observed this issue
**Environment:**

- Baremetal Operator version: latest master
- Environment (metal3-dev-env or other):

/kind bug

**Comment by elfosardo** [comment]
@emailallau that looks like sgdisk has found MBR instead of GPT data
was the disk partitioned externally or maybe reused?
I any case it's not related to UEFI or BMO.
Can you please provide the logs from the ironic-python-agent running during the deployment?

**Comment by Rozzii** [comment]
Also if it is fine by you @emailallau please report this issue on Ironic or Ironic-python-agent bug tracker instead of here.
Ironic bug tracker: https://launchpad.net/ironic
Ironic-python-agent bug tracker: https://launchpad.net/ironic-python-agent
Please provide all the logs from the ironic-python-agent when you create the bug reports, If you have any question I would recommend getting in touch with the Ironic devs on IRC: https://wiki.openstack.org/wiki/Ironic#IRC

**Comment by Rozzii** [comment]
/remove-lifecycle stale
As it turns out dev-env has some issues with uefi in case of centos images https://github.com/metal3-io/metal3-dev-env/pull/1326
/triage accepted

**Comment by Rozzii** [comment]
I have put back the  invalid label and the stale because although the dev-env has issues, this specific ticket is talking about different non Metal3 problems.
