### ISSUE TITLE
The current IPAM in the PR for ironic+bmo inhibits use of cache

### ISSUE THREAD

**Issue by imain** [metal3-io/baremetal-operator#251]
Currently the ip-set container is run after the image downloading is done via ipa-downloader and rhcos-downloader.  This was intentional as we're not sure how long these operations would take.  Unfortunately when originally scheduled on a master, the provisioning interface has an IP given to it via DHCP, so the cache download from the pod works fine.  If we try to run it a second time we find that the IP for the provisioning interface has been removed (and not replaced - there's no DHCP server anymore), and the download fails.

**Comment by imain** [comment]
I'm writing this down because CI will always work for this, but in the real world there could be an issue if the pod restarts for any reason.

**Comment by russellb** [comment]
Any reason we can’t do this download on the external network instead of the
provisioning network?

Sent from mobile device

On Jul 8, 2019, at 7:21 PM, Ian Main <notifications@github.com> wrote:

I'm writing this down because CI will always work for this, but in the real
world there could be an issue if the pod restarts for any reason.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/metal3-io/baremetal-operator/issues/251?email_source=notifications&email_token=AACLQCXUERXJ66ZSRJXHNR3P6PDXXA5CNFSM4H7AHDRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZOT3KA#issuecomment-509427112>,
or mute the thread

**Comment by imain** [comment]
Yeah so I need to look into this networking:

[core@master-0 ~]$ curl http://192.168.111.1:80/
curl: (7) Failed to connect to 192.168.111.1 port 80: No route to host
[core@master-0 ~]$ curl http://192.168.111.1:8080/
curl: (7) Failed to connect to 192.168.111.1 port 8080: Connection refused

I'm guessing it's firewalled?

**Comment by imain** [comment]
But yes, you're right, that's the best fix here.

**Comment by imain** [comment]
Yeah it's firewalled still, will update httpd container.

**Comment by hardys** [comment]
Ok sounds like this will be closed via https://github.com/metal3-io/ironic-image/pull/69

**Comment by dhellmann** [comment]
@imain the PR @hardys linked to is closed. Should this issue be closed?
