### ISSUE TITLE
adoption of master nodes fails

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#271]
After building a new cluster my master nodes in ironic have status "adopt failed" with the error "Error while attempting to adopt node e0759af0-55f0-4e47-a1c7-baeaccd67f61: Cannot validate image information for node e0759af0-55f0-4e47-a1c7-baeaccd67f61 because one or more parameters are missing from its instance_info and insufficent information is present to boot from a remote volume. Missing are: ['ramdisk', 'kernel', 'image_source']."

**Comment by zaneb** [comment]
Sounds like it worked with Ironic running on the provisioning host, likely because something in the installer sets the `image_source` to `'http://172.22.0.1/images/rhcos-ootpa-latest.qcow2'` (the other parameters mentioned in the error aren't actually needed because we use a whole-disk image), but not on a freshly-spawned Ironic running in the cluster.
