### ISSUE TITLE
verify_ca needs to be populated

### ISSUE THREAD

**Issue by yrobla** [metal3-io/baremetal-operator#392]
There is a need for a flag to instruct ironic to validate certificates or not. This can be specific for drivers (https://docs.openstack.org/ironic/pike/admin/drivers/redfish.html), but generally all drivers should implement it. This is needed in the case of non-trusted certs, to disable validation. This parameter should be passed to the ironic nodes in order to enable/disable validation, so we need to expose it here as part of bmc details, then propagate it to ironic.
Additionally, installer will pass the right config from install-config.yaml

**Comment by dhellmann** [comment]
There was some discussion of this on the mailing list: https://groups.google.com/d/msg/metal3-dev/unZaLdalLXI/Jejgeyn4EQAJ

**Comment by maelk** [comment]
There is a related issue with redfish parameters : #286 (maybe duplicate?)

**Comment by yrobla** [comment]
I guess it can be considered a duplicate, but it covers the idea from a different point of view. What we talked about in the thread is the need to have extra parameters, and not specifically for redfish. The idea is to add a verify_ca parameter in the bmc structure, but that's not specifically for redfish but for all the drivers. I also proposed the idea of passing that in the URL but seems that a better and clear way to do it, is just add the parameters needed in the bmc struct.
@maelk I started to work on that on the weekend, but giving the fact that you also started that PR, what do you prefer, amend your PR to reflect that verify_ca parameter, or that i send my PR ?

**Comment by zaneb** [comment]
What Doug proposed in the thread is consistent with what [I suggested](https://github.com/metal3-io/baremetal-operator/issues/286#issuecomment-524879669) on the other issue when we last discussed it back in August (i.e. make it part of the BMC details that's generic to all drivers, don't require each driver to divine it from the URL). Since Maël said that he ran out of time for looking into this, I'm sure he'd be happy if you went ahead and submitted your PR ;)

**Comment by yrobla** [comment]
Ok working on it on a local fork, i will send as soon as i have it working with tests

**Comment by maelk** [comment]
yes, please go ahead :D
