### ISSUE TITLE
Use ownerReferences instead of ConsumerRef

### ISSUE THREAD

**Issue by maelk** [metal3-io/baremetal-operator#399]
In order to make things consistent with how CAPI works, for pivoting, OwnerReferences could be used instead of CustomerReference to link to the machine or baremetal machine consuming the bmh. We need to investigate the impact of such a change, especially in terms of determining the availability of a bmh and in terms of pivoting, when the resources are moved from the management cluster to the target cluster.

**Comment by maelk** [comment]
@dhellmann @russellb @zaneb Do you already see any blockers for this ?

**Comment by zaneb** [comment]
I think I might have asked this before, and the problem was that deleting the Machine would result in the Host being deleted, which is never what you want (except I guess during pivoting).
If we have a Finalizer on the Machine that removes the ownership reference from the Host before the Machine can be deleted (as we do already), then it might work? (I'm not clear on when exactly garbage collection kicks in.)

**Comment by maelk** [comment]
yes, we definitely need to carefully handle the deletion of the machine / baremetal machine. The owner can however be deleted without deleting the children, they are then orphaned, depending on the strategy

**Comment by maelk** [comment]
This was completed
/close
