### ISSUE TITLE
Support complete set of root device hints

### ISSUE THREAD

**Issue by yrobla** [metal3-io/baremetal-operator#400]
Currently only device name and HCTL are supported in HardwareProfile for Root Device Hints. While ironic is supporting a much more complete set of hints: https://docs.openstack.org/ironic/train/install/advanced.html#specifying-the-disk-for-deployment-root-device-hints

In real baremetal environments its not uncommon to see device names change between boots, names like /dev/sda in one boot can become /dev/sdb. Likewise the hctl can change. In order to work on hardware where this happens we will need to work with disk size, serial numbers or wwn. 

So matching the possibilities of ironic in terms of root device hints is an important feature for baremetal deployments.

**Comment by juliakreger** [comment]
I recently had a chat with a server vendor that was encountering similar issues. Essentially the OS installation was ending up on the wrong device, where as size matching would have solved the issue because they wanted the OS deployed to a specific mirror set. As such, I think it is reasonable to prioritize any work around enhancing the hints that can be offered through.

**Comment by dhellmann** [comment]
We had originally planned to implement this by defining [host profiles](https://github.com/metal3-io/metal3-docs/pull/4) that could be configured by a user and that would be selected automatically by matching hardware characteristics with an option for the user to override that. We only implemented enough to do basic hints with no option for defining new values and no hardware matching.

Given the experience we've gained since that original design, and the work on a [separate hardware classification controller,](https://github.com/metal3-io/metal3-docs/pull/60) I think the current HardwareProfile field is the wrong way to manage the deployment hints and we should just add a field or set of fields for those directly to the host spec somewhere. We can then deprecate the profile matching portion of the baremetal operator completely, and allow the classification and deployment hints to be separate concerns.

**Comment by stbenjam** [comment]
Related design proposal: https://github.com/metal3-io/metal3-docs/pull/60

**Comment by maelk** [comment]
We also need something similar, allowing us to pass the rootdevicehint in the BMH. I think this is not related to metal3-io/metal3-docs#60 because we want to give a specific rootdevicehint for a specific node, while that proposal rather compare the hardware from introspection to validation profiles but does not set anything else than labels, and specifically not the rootdevicehint. Additionally a bmh could match several of those validation profile so we cannot define the rootdevicehint there. @mikkosest is working on this so if nobody else is already working on it too (@yrobla ?) then we'll keep going with this, adding the rootdevicehint into the BMH

**Comment by yrobla** [comment]
I still haven't started the work, just proposed the idea. And i think that the approach that you are trying is the same as I'd like, adding root device hint on BMH. I'd be happy to collaborate with @mikkosest for the task.

**Comment by zaneb** [comment]
I think there's some confusion about @stbenjam's comment. #60 is related in the sense that the functionality that is currently being provided by the "hardware profile" will end up in two different places. The stuff in #60 covers the hardware classification, and this issue covers the root device hints. The doc in #60 does not describe an implementation of root device hints; there is no currently open PR for this issue that I'm aware of.

**Comment by mikkosest** [comment]
I made a PR about the rootdevicehint issue https://github.com/metal3-io/baremetal-operator/pull/442. Could you check @stbenjam @yrobla @dhellmann @maelk @zaneb ?

**Comment by stbenjam** [comment]
Sorry I may have linked the wrong one: https://github.com/metal3-io/metal3-docs/pull/76 covers root device hints.

**Comment by dhellmann** [comment]
This was implemented in https://github.com/metal3-io/baremetal-operator/pull/495
