### ISSUE TITLE
 BMH registration sporadically takes a long time (10-15 mins)

### ISSUE THREAD

**Issue by jezogwza** [metal3-io/baremetal-operator#519]
BMO registration sporadically takes a long time (10-15 mins for some hosts). This can delay a deployment quite a bit. Specially if it happens during the deployment of the control plane host, which CAPCPK does serially.

Seems to be something around this code or call.
https://github.com/metal3-io/baremetal-operator/blob/c3da1db56f435a2419945097ab84b0d9678bb730/pkg/provisioner/ironic/ironic.go#L203-L417

Is this Ironic or a BMO issue?

I missed the suggestion from the google doc to gather:
_ironic-api and ironic-conductor logs
`openstack baremetal node list` while it’s stuck (or `openstack baremetal node show`)_
Will attach that next time this occurs.

In the meantime, as an example , attached are three files :
- Baremetal Operator logs : baremetal_operator_2.txt
- ironic logs : ironic_2.txt
- describe of the host in question. describe_2.txt

Registration took 11 mins for this host, specifically it  occurred between : 
      End:             2020-05-13T14:55:38Z
      Start:           2020-05-13T14:44:37Z

[baremetal_operator_2.txt](https://github.com/metal3-io/baremetal-operator/files/4622923/baremetal_operator_2.txt)
[describe_2.txt](https://github.com/metal3-io/baremetal-operator/files/4622924/describe_2.txt)
[ironic_2.txt](https://github.com/metal3-io/baremetal-operator/files/4622925/ironic_2.txt)

**Comment by maelk** [comment]
Thank you for the issue Rodolfo

**Comment by zaneb** [comment]
So as you can see in the event list, initially the BMC is registered pretty quickly, and it's re-registering again later that is slow.

Looking at the logs the initial registration lasted from 14:39:34-14:40:03, so <30s. Hardware inspection then begins. At 14:44:14 the hardware inspection results become available and the Host moves to the Ready state. *However*, in Ironic the server remains in the `inspect wait` state. This is likely to have some significance for our problem.

Then the controller appears to requeue in tight loop (i.e. with 0 delay) for a bit. That's a weird thing to happen in Ready state, and might be a bug. In the middle of this burst, there's one write conflict. That may be an indication that the resource was changed by something external.

Then, it reinitiates registration, apparently because the credentials changed. Perhaps that's what cause the write conflict?

The registration doesn't succeed right away - possibly because Ironic is still in the `inspect wait` state. Instead it requeues a few times (with no delay), then after requesting a requeue without delay at 14:44:43, there are no more reconciliations until 14:55:38.

Now 10 minutes later, the Host is reconciled again. By this time Ironic has reached the `manageable` state, and re-registration completes immediately.

At 14:56:07 provisioning starts, and presumably everything proceeds normally from there (the log ends shortly after).

**Comment by zaneb** [comment]
@mhrivnak does the operator-sdk throttle requeues if you accidentally get the operator stuck in a hot loop? That together with the issue fixed in #531 would explain everything.

**Comment by mhrivnak** [comment]
> @mhrivnak does the operator-sdk throttle requeues if you accidentally get the operator stuck in a hot loop? That together with the issue fixed in #531 would explain everything.

If your Reconcile function returns with `Requeue: true`, then yes, controller-runtime [queues a new request with rate limiting](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.5.2/pkg/internal/controller/controller.go#L272). The same happens if Reconcile returns an error.

**Comment by kanwar-saad** [comment]
+1 We are seeing this issue as well.

**Comment by zaneb** [comment]
The pattern of delays doesn't seem to match what you might expect given how the rate limiting appears to work, so there may be something else going on. Still, it would be interesting to see if the issue is still reproducible with the fix in #531.

**Comment by jezogwza** [comment]
Ok will be testing with these fix , and will report back if we see a difference.

**Comment by jezogwza** [comment]
After deploying a couple of clusters each twice , and not experiencing this delay. I think  this was resolved.  Unfortunately because reproducing this was non deterministic, we cannot say with 100% certainty. That might come with time. But at the moment we feel that  It appears as if #531 did indeed solve this.

**Comment by stbenjam** [comment]
Great news! Please feel free to re-open if you see the problem again.

/close
