### ISSUE TITLE
Automatically configure the switch before baremetalhost configuration

### ISSUE THREAD

**Issue by zhouhao3** [metal3-io/baremetal-operator#570]
Hi, Metal3 community.  We would like to implement this [prototype](https://github.com/metal3-io/metal3-docs/blob/master/design/physical-network-api-prototype.md) to automate configuring switch before baremetalhost provisioning, for example, join a specific baremetal server to a specific vlan. 
In order to do that, baremetal-operator needs to obtain the following outside information.: 

- which port the baremetal server is connecting

- which vlan the baremetal server need to join

- the information about switch such as OS

Here are some basic design for the implementation:

New switch secret is used to save the relevant information of the switch, so that you can perform related configuration operations on the switch through ansible later.
```
switch secret {
  username: string 
  password: string
}
```
Add new field to BareMetalHostSpec spec
```
BareMetalHostSpec {
  ...
  ConnectTo *switch
}
```
```
switch {
  // switch version info
  SwitchOS: string
  IPAddress: string
  // switchSecret is the name of the secret which is used to access the switch
  SwitchSecret: string
  // Vlan to connect
   Vlan {
         name: string
         id:  int
   }
   // Port is the port of the switch which the baremetal server is connected to
   Port: int
}
```
Add handle to switch changes in baremetalhost_controller.go:
```
func Reconcile() {
     ...
     // step1: verify the existence of new and old vlan to the switch
     // step2: delete the port from the old vlan
    // step3: add the port to the new vlan
}
```
For configuring the physical device, we plan to use Ansible as the backend like [prototype-a-physical-network-api](https://github.com/metal3-io/metal3-docs/blob/master/design/physical-network-api-prototype.md) proposed.

The following is how to configure VLANs when deploying bare-metal servers:

Store the username and password of the switch into the cluster in the form of secret.
Add or change the relevant information of the switch in BMH CR, which will trigger the Reconcile in baremetalhost_controller.
In Reconcile, it is determined that the ConnectTo field is changed, and then ansible will be triggered to connect to and configure the switch.
What do you think?

**Comment by dhellmann** [comment]
I do not think the baremetal-operator should be responsible for trying to change the switch settings. A new controller for the Switch type should do that.

The Switch API should be defined to avoid ambiguous or conflicting settings. For example, placing the port ID on the host means that multiple hosts can be configured to be attached to the same port. If instead the Switch has a list of ports, and for each port it has the settings for things like VLANs, then it would be clear what settings should be used for each port and conflicts would be resolved by modifying the Switch resource.

The status portion of the Switch resource would report what is connected to each port and what VLANs are active on the ports. We may actually want to have a separate SwitchPort resource to reduce collisions when writing to the Switch. The controller for the Switch could create the SwitchPorts as part of reconciling the Switch.

The status for the Switch or SwitchPort resource should show what is connected (by MAC?) and what VLANs are active. That way callers who want to change the settings can tell when the changes have been applied.

The cluster-api-provider-metal3 is responsible for orchestrating the process of finding a host and provisioning the image onto it. We can add switch management to those steps, so that the ports are configured before the image is deployed.

How, though, does anything know which VLANs to use? Are those defined at the cluster level? Recorded on the Machine?

We should probably use a design document in the metal3-docs repository to work out the implementation plan for this.

**Comment by q384566678** [comment]
> A new controller for the Switch type should do that.

agree

> How, though, does anything know which VLANs to use? Are those defined at the cluster level? Recorded on the Machine?

Our idea is to add switch and vlan related information at the cluster level.

The approximate implementation process is as follows:
1. Add Switch resource:
```
Switch
Spec: {
AccessDetail
Vlans
}

Status: {
SwitchPorts
CurrentVlans
}
```
Baremetal Operator is responsible for calling Ironic to detect the port information of the switch connected to the bare metal, which is saved in [Bmh status hardware](https://github.com/metal3-io/baremetal-operator/blame/master/docs/api.md#L175).The Switch controller then monitors this data and writes it to SwitchPort.Status:

```
SwitchPort
Spec: {
Vlan {
 name
 ID
 }
}

Status: {
Mac // Ironic > bmh > switchport
PortID // Ironic > bmh > switchport
Switch
CurrentVlan {
 name
 ID
 }
}
```
In this case, you will get the port of each switch connected to BMH.
2. Add switch and VLAN information to the cluster spec, indicating the switch and VLAN to which the cluster belongs.
```
Cluster
Spec: {
APIEndpoint
Vlan {
 Name
 ID
 OwnerRef
 }
}
```
3.  add machine to cluster
     1. Search bmh
          1. Bmh ready
          2. Configure switch
               1. According to the Mac address of Bmh, find the corresponding Switch Port. (All the corresponding information is already stored in BMH Status Hardware, you only need to find the corresponding value)
               2. Configure Port, modify SwitchPort Spec(Trigger the switch controller to set the port to the specified vlan to complete the configuration.)
4. Switch controller
After the Switch controller is triggered, it will get the basic information of the switch in the cluster and the port and VLAN to be switched, and then call ansible to perform these operations.
The Switch controller then monitors all the Bmh status and updates the SwitchPort status, and judges whether the operation is completed according to the SwitchPort status.
This is one of our preliminary implementation methods, and any suggestions are welcome.

**Comment by maelk** [comment]
The BMH could also reference the switchPort objects. However, I think that putting the configuration at the cluster level is going to be problematic. In my opinion, the switch configuration should be its own object and referenced at the metal3machine level (or, for KCP and machine deployments) in a Metal3MachineTemplate, and applied on the ports referenced by the BMH. That however supposes an homogeneous hardware setup (that is the case anyways for KCP and machine deployements). 

The BMH could have in its spec a map linking an arbitrary interface names with a switchPort reference. The Metal3Machine(Template) would also have a map linking the same arbitrary names to switchPortConfiguration objects. So before starting provisioning the BMH, the network controller would apply the configuration to the switchPort and set a flag in the switchPort "Configured:true" for example. Once all switchPorts are configured, BMO would start the deployment of the BMH.

Upon deletion of the Metal3Machine, the linking between the switchPort and the SwitchPortConfiguration would be remove and the port unconfigured, or configured to a default configuration, maybe defined as its own object by the user (so that it would automatically boot over PXE properly for discovery for example).

The potentials of such runtime network configuration are high, but we need to be careful to design the whole API properly, or we'll very easily put limits on what can be achieved and how usable it is. I would suggest to move all this to a google doc for collaboration editing.

**Comment by q384566678** [comment]
I created a [file](https://docs.google.com/document/d/1l2OIM6pxo3bX99ccPsLtjKlSsiXZFAU4Dvx6OIa_M3k/edit#) in google doc and shared it with metal3 group, you can view and edit directly.

**Comment by maelk** [comment]
Thank you. Could you however please fill it in in the template please ? That helps getting all the required points down in the docs.
You can find the template here : https://github.com/metal3-io/metal3-docs/blob/master/design/_template.md

**Comment by q384566678** [comment]
thanks, updated.

**Comment by maelk** [comment]
Thank you. let's move the discussion there then

**Comment by q384566678** [comment]
@dhellmann  @maelk We have updated this [document](https://docs.google.com/document/d/1l2OIM6pxo3bX99ccPsLtjKlSsiXZFAU4Dvx6OIa_M3k/edit#) and I hope you can take a look. Any comments are welcome.

**Comment by zaneb** [comment]
A few months back I wrote up some notes on what [a multi-tenant system using Metal³ might look like](https://governance.openstack.org/ideas/ideas/teapot/index.html). That's not the only possible shape for such a system, but it might be useful in describing a concrete use case that you can compare the design against to determine if it meets likely user needs and if the concerns are correctly separated.

**Comment by zhouhao3** [comment]
We revised the document based on your suggestions and added some user cases and workflows. Hope you guys can take a look.
