### ISSUE TITLE
Configurable disk cleaning options

### ISSUE THREAD

**Issue by kashifest** [metal3-io/baremetal-operator#626]
This is a feature request. The user story is as follows: 

**User story:**
As a user, I want to clean up the disks associated with a node in a configurable way. For example, during the initial provisioning I want all the disks of a particular node to be cleaned. However, during an upgrade procedure, I want to clean only the root disk associated with that node and leave the other disks uncleaned as we have data on it and we don't want it to be erased. I want to communicate this information to ironic through the bmh CR. 

This will also require ironic to understand the request coming from BMO to clean disks associated with a node in a configurable way. A similar feature request towards ironic is also being requested. Note that, the default cleaning path will still be the same i.e. cleaning all the disks as it is done today. We only want to make the cleaning configurable runtime. On BMO side, the change foreseen is an api change to communicate the desired configuration to ironic, the configuration being either clean root disk only or clean all the disks.

**Comment by dtantsur** [comment]
An extract from the IRC discussion:
```
13:14 <fmuyassarov> dtantsur, It is coming from upgrade use-case. For example, when we do the k8s cluster upgrade the nodes will be deprovisioned & provisioned. So, we don’t want to lose disk data. However, in normal scenarios we still want to make sure that while provisioning we do cleaning for all the disk. One way to do it is to have two ironic images (one for upgrade, another for normal use cases) with two differen
13:14 <fmuyassarov> t configurations, but I don’t think it is a good idea to have two ironic containers running.
13:15 <dtantsur> fmuyassarov: what's the reason of doing upgrades via reprovisioning?
13:29 <fmuyassarov> dtantsur, Because, we are using the Cluster API KCP (KubeadmControlPlane) upgrade feature.  And while upgrading, KCP deletes a Machine which will cause Metal3Machine deletion and finally BareMetalHost deprovisioning. So, AFAIK Metal3 doesn’t have a way to control that behavior since it happens on a higher level.
13:29 <fmuyassarov> So, it deleted a Machine and recreates a new one.
13:48 <dtantsur> sigh
13:48 <dtantsur> I wonder if we can somehow hold it from actual deprovisioning?
13:49 <dtantsur> in addition to cleaning problems, it's also going to be time-consuming
13:53 <fmuyassarov> TBH I don't think that there is a way to avoid a BMH going through deprovisioning since KCP deletes the associated Machine object.
13:56 <dtantsur> fmuyassarov: yeah, but we could keep BareMetalHost in some new "pending" state until it gets picked again?
13:57 <fmuyassarov> dtantsur, just a heads up. Here is an issue where we will discuss it with Metal3 folks as well. https://github.com/metal3-io/baremetal-operator/issues/626
13:57 <dtantsur> yep, already subscribed
13:57 <dtantsur> but I still wonder if the upgrade problem has to be solved on some upper level
13:57 <dtantsur> because reprovisioning can easily take tens of minutes
```

**Comment by fmuyassarov** [comment]
Copying my last reply here:

Yes, we could use for example unhealthy annotation on BMO that would avoid that BMH to be selected for while. However, I'm not sure if it is possible to attach a provisioned BMH to a new Metal3Machine.

**Comment by maelk** [comment]
Would not cleaning at all the node during an upgrade be a solution ? If we do not clean, IPA will deploy the new image on the root disk, hence overwriting it, leaving the other disks unchanged. Is that correct ?

**Comment by dhellmann** [comment]
As @dtantsur hints with his response, I think we'll do better solving this if we separate the goals and implementation details in the user story. For example, it might be better to say "As a user, I want to upgrade a node in my cluster without losing data on secondary storage devices in the host." There are a few ways to do that.

In OpenShift, we upgrade in place using an operator running in the cluster. Metal3 isn't involved, so there is no risk of cleaning causing data loss. It sounds like that approach isn't compatible with the Cluster API, though.

We could, as is proposed here, provide a way to control which individual devices should be cleaned as part of deprovisioning a host. We also need to manage what happens during provisioning, though, so when the RAID work is done it needs to take those same rules into account. And we would need to make Ironic understand those more detailed cleaning instructions.

However, for an upgrade, it's not clear that we want to clean anything. It might be simpler to make metal3 clean _nothing_ on the host during deprovisioning, at least in some cases. That would allow a host to be recycled without updating anything other than writing the new image to disk, and whatever supporting operations are needed for that. We would need to preserve enough state in the status fields so that when the host is reprovisioned we know not to reconfigure the RAID, etc. Would Ironic need any changes to make that work? How would metal3 recognize the difference between normal deprovisioning and the recycling case for upgrade?

We should explore both of those options further, and see if there are others.

At the same time, we need to understand what it's going to mean to recycle a host in this way. If the data on the secondary storage is important, presumably something knows where it is. How does that consumer refer to the data? Is the reference linked to a node that is going to be removed as part of the upgrade process? If so, how is anything using the storage going to find its data again later? Will the host cause a new node with the same name to be created when the host comes back online after the upgrade? What about any other references to assets on the host, like special hardware devices (network cards, GPUs, etc.)?

**Comment by kashifest** [comment]
> Would not cleaning at all the node during an upgrade be a solution ? If we do not clean, IPA will deploy the new image on the root disk, hence overwriting it, leaving the other disks unchanged. Is that correct ?

Yes, that's what we want , but with the current setup, no cleaning can be configured by configuring the following variables
```
erase_devices_metadata_priority
erase_devices_priority 
```

 ironic.conf, and it would mean we would need to use separate ironic images for provisioning (where all disk erase is desirable)  and upgrade which is undesirable.

**Comment by dtantsur** [comment]
There is a trick to reverse the logic. Automated cleaning can be disabled by default in the configuration (`automated_clean = False` in ironic.conf) and then enabled on demand per node (via the `automated_clean` field). BMO would still need to know if we're unprovisioning or just upgrading.

**Comment by dtantsur** [comment]
I've also filed https://storyboard.openstack.org/#!/story/2008113 to allow disabling cleaning per node.

**Comment by zaneb** [comment]
> On BMO side, the change foreseen is an api change to communicate the desired configuration to ironic, the configuration being either clean root disk only or clean all the disks.

The issue I have with this is that such an API is not declarative. You have to run a little workflow to first set up the way you want the action to happen, and then to do it.

A declarative API would look like some long-term field recording that the Host is assigned to some given thing, such that the Host won't be cleaned as long as that field remains unchanged. An obvious candidate for this would be the ConsumerRef, but for the fact that in your case the CAPI is deleting the Machine and thus removing the ConsumerRef.

In my v2 API proposal that I never I have time to work on, I floated the idea that if we had a separate BareMetalHostAllocation resource, that we could implement it such that disks were never cleaned during the lifetime of that resource. In a multi-tenant environment, that would mean that the tenant to whom a Host is allocated would not have a way of forcing cleaning though, so even this requires more thought.
