### ISSUE TITLE
[Feature] External provisioner integration (ansible?) using hooks?

### ISSUE THREAD

**Issue by s3rj1k** [metal3-io/baremetal-operator#634]
Would be nice to have some kind of integration with arbitrary provisioner in multiple lifecycle of operator.
Some kind  of hooking mechanism.

This is somewhat related to issue with ansible integration part https://github.com/metal3-io/baremetal-operator/issues/570

**Comment by zaneb** [comment]
There is already a separate API for the provisioner within the baremetal operator, and we're definitely not opposed in principle to more implementations other than ironic.
That said, this would be a substantial project in itself, and it's probably unrealistic to expect folks who are already active in the community to write one because the provisioner we have keeps us plenty busy. So it's probably up to you to write it :)

**Comment by s3rj1k** [comment]
@zaneb Thanks for a reply, do you have any ideas on how to add external calls to the ironic provisioner itself, without actually forking it?

I mean something like an blocking event system or hooks.

**Comment by zaneb** [comment]
Ah, sorry, I misinterpreted the question. You don't want to reimplement the provisioner, just to add hooks where something external can be called at particular points in the lifecycle.

I think that's a reasonable request, but in order to implement it it would be helpful to know the kinds of places where you want to implement a hook. [Provisioning state transitions](https://github.com/metal3-io/baremetal-operator/blob/master/docs/baremetalhost-states.md#readme) are an obvious one that could probably be made robust. I'd be worried if you had to hook in to e.g. state transitions in Ironic or something more fine-grained like that.

One way to implement the former that you might not have considered is in a validating webhook. You could do that without touching the baremetal-operator code at all.

**Comment by s3rj1k** [comment]
@zaneb Yes, I was thinking about _Provisioning state transitions_ PRE and POST hooks.

Also can you be a bit more specific about `validating webhook` that you mentioned?

**Comment by zaneb** [comment]
So there is an admission controller called [ValidatingAdmissionWebhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook), which basically delegates validation of a change to an object to a webhook (you can specify multiple webhooks; they all have to approve for a write to be accepted). [kubebuilder](https://book.kubebuilder.io/reference/admission-webhook.html) can generate the skeleton of one for you. We're planning to switch to kubebuilder (from an old pre-kubebuilder version of operator-sdk) soon to make this easier.

The main job of the webhook is to reject a request if it decides the contents are not valid, but there's no reason you can't write one with side effects. By default calls time out after 10s, but it's configurable. (Note that you are blocking the controller while it's trying to write to the object while the webhook is running, though.)

I believe you get a copy of the new and old object state, so you could compare them to see if the state is changing and run your hook, then either block until it completes or reject requests until it completes (I could see us potentially implementing some special error handling to detect this case in the operator and requeue after a delay rather than returning a write error that may cause a hot loop).

**Comment by dhellmann** [comment]
What would hooks do that a separate controller couldn't do?

**Comment by s3rj1k** [comment]
@dhellmann Possibly easier and quicker development.
No need to write separate controller.

**Comment by zaneb** [comment]
> What would hooks do that a separate controller couldn't do?

This is a good question, and I agree that as much as possible things should be implemented externally using the k8s API rather than in go code with all the messy vendoring (and internal API stability) that implies.

As I understood it the requirement is to be able to implement blocking (i.e. don't change state until this external thing has been done). That isn't possible with an external controller just watching the resource and reacting, although it is possible with a validating webhook.

**Comment by s3rj1k** [comment]
@zaneb Yea, blocking is needed in-between state changes.
