### ISSUE TITLE
baremetalhost can't download /undionly.kpxe from tftp

### ISSUE THREAD

**Issue by TonyZhang1989** [metal3-io/baremetal-operator#718]
baremetalhost  can get ipaddress from dhcp server, but still can't download /undionly.kpxe file . 

19:55:56.294507 b4:96:91:4c:93:c4 > b4:96:91:4c:95:bc, ethertype IPv4 (0x0800), length 73: 192.168.100.139.2071 > 192.168.100.111.69:  31 RRQ "/undionly.kpxe" octet tsize 0

my environment:
1. the size of "/shared/tftpboot/" is 70KB
2. kubernetes v1.18.10
3. CentOS 7.6 x86_64

pictures: 
[https://ibb.co/6t6v1Zn](url)

**Comment by sumitjadhav1** [comment]
Hi @TonyZhang1989 , could you please let us know whether tftp download worked correctly for you in BIOS/UEFI mode...? Wanted to confirm since you closed this issue within couple of days. We are also facing similar issue as in [metal3-dev-env#491](https://github.com/metal3-io/metal3-dev-env/issues/491)
