### ISSUE TITLE
Provide steps that allows dropping fields from public API.

### ISSUE THREAD

**Issue by s3rj1k** [metal3-io/baremetal-operator#874]
We need a design doc that can describe a process of deprecating any (unneeded) struct fields in public.

One example would be PR https://github.com/metal3-io/baremetal-operator/pull/850 that introduces new field in public API that describes disk type and this field supersedes `Rotational` field.

So evidentially it would be nice to deprecate `Rotational` field from public API.

**Comment by zaneb** [comment]
There's no great mystery: you create a new API version, and you write a conversion webhook to convert between the different versions. The documentation is here: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

The question is whether you would bother to do this in order to remove a single redundant boolean from the hardware details.

We do need to declare a more stable (beta at least) API at some point, but it will be a ton of work. Maybe we should open an issue to keep a running list of the things we want to remove when we do that.

/close

**Comment by dhellmann** [comment]
@zaneb The technical details of the process are clear, but I don't think we've documented our deprecation and support policy for older API versions anywhere. Maybe I just couldn't find that doc?

**Comment by zaneb** [comment]
Yeah, I'm not aware that that doc exists, although CAPM3 has gone through several API revisions so it's possible - I haven't looked.

For BMO specifically, we don't have any older API versions so it'd be pretty academic.
