### ISSUE TITLE
Track works left in #929

### ISSUE THREAD

**Issue by hs0210** [metal3-io/baremetal-operator#959]
This issue is mainly used to track the works left in #929:
1. fix a [bug](https://github.com/metal3-io/baremetal-operator/pull/929#issuecomment-905393078) that may be on the ironic side
2. revert PR929 to continue #882 with #958

**Comment by hs0210** [comment]
@dtantsur @zaneb We can continue the discussion here.

**Comment by hs0210** [comment]
A bug likely in ironic occurred when solving [clean failed problem in prepare state](https://github.com/metal3-io/baremetal-operator/pull/929#issue-681489120) using target state to distinguish manual and auto clean failure. 
The following is the bug and this is the complete log [ironic-conductor.log](https://github.com/metal3-io/baremetal-operator/files/7080512/ironic-conductor.log)
> Unexpected error when processing next clean step. TypeError: 'NoneType' object is not subscriptable

The following is the patch.
```diff
diff --git a/pkg/provisioner/ironic/ironic.go b/pkg/provisioner/ironic/ironic.go
index 282363e3..64c481dd 100644
--- a/pkg/provisioner/ironic/ironic.go
+++ b/pkg/provisioner/ironic/ironic.go
@@ -1105,6 +1105,21 @@ func (p *ironicProvisioner) Prepare(data provisioner.PrepareData, unprepared boo
                        result, err = p.setMaintenanceFlag(ironicNode, false)
                        return
                }
+               if ironicNode.TargetProvisionState == string(nodes.Available) {
+                       result, err = p.changeNodeProvisionState(
+                               ironicNode,
+                               nodes.ProvisionStateOpts{Target: nodes.TargetManage},
+                       )
+                       if err != nil {
+                               return
+                       }
+                       time.Sleep(10 * time.Second)
+                       result, err = p.changeNodeProvisionState(
+                               ironicNode,
+                               nodes.ProvisionStateOpts{Target: nodes.TargetProvide},
+                       )
+                       return
+               }
                result, err = p.changeNodeProvisionState(
                        ironicNode,
                        nodes.ProvisionStateOpts{Target: nodes.TargetManage},
```

**Comment by dtantsur** [comment]
Jacob and I are looking into the ironic cleaning code to understand what goes wrong. Meanwhile, there seems to be an issue with your patch:

> if ironicNode.TargetProvisionState == string(nodes.Available) 

Did you mean

> if ironicNode.ProvisionState == string(nodes.Available) 

? If the target state is set, you cannot execute new actions.

**Comment by zaneb** [comment]
> Jacob and I are looking into the ironic cleaning code to understand what goes wrong. Meanwhile, there seems to be an issue with your patch:
> 
> > if ironicNode.TargetProvisionState == string(nodes.Available)
> 
> Did you mean
> 
> > if ironicNode.ProvisionState == string(nodes.Available)
> 
> ? If the target state is set, you cannot execute new actions.

It was your idea: https://github.com/metal3-io/baremetal-operator/pull/929#issuecomment-903921236

**Comment by dtantsur** [comment]
Ah, wait, we're in the `clean failed` path. Yes, this is correct, I forgot about it. Sorry.

https://review.opendev.org/c/openstack/ironic/+/807105 will make sure we have a proper traceback in this case. For now I'm trying to guess what happened.

**Comment by dtantsur** [comment]
I've taken a closer look at the iRMC RAID implementation and the conductor logs, and I think I've spotted two problems: 1) the RAID interface does not reboot the node after RAID is built, 2) cleaning is over before the job is actually finished.

1) Metal3 operates in the so called "fast track" mode, which means that the IPA ramdisk stays on unless explicitly stopped.  After iRMC RAID is done, the ramdisk stays on, no wonder that the automated clean fails. The reason it works on the 2nd try is because every time an error happens, ironic breaks the "fast track" mode and forces one reboot on the next action. This issue should be fixed in Ironic. You need to reboot after RAID is done and wait for IPA to come up again. Check other RAID implementations for how to do so.

2) I'm still investigating, what exactly has happened, but in your logs RAID configuration is over at 08:43:16, while automated cleaning started at 08:39:36. Which, again, causes the automated clean to fail because the two processes race against each other.

**Comment by dtantsur** [comment]
From the Redfish implementation. This is how you tell Ironic that you're polling for completion: https://opendev.org/openstack/ironic/src/branch/master/ironic/drivers/modules/redfish/raid.py#L849-L853. Without this Ironic will check IPA for any running steps, and if there are none, it will proceed to the next step.

And this is how you request a reboot after RAID is built: https://opendev.org/openstack/ironic/src/branch/master/ironic/drivers/modules/redfish/raid.py#L854-L858

**Comment by dtantsur** [comment]
I've written https://review.opendev.org/c/openstack/ironic/+/807295 to make writing such tasks simpler.

**Comment by hs0210** [comment]
@dtantsur Thanks for your thorough investigation.

> 1)  the RAID interface does not reboot the node after RAID is built

This is indeed a bug that needs to be fixed, we will fix it.

> 2) cleaning is over before the job is actually finished.

> RAID configuration has completed on node 8a7c5dde-dec4-4406-bf0c-ebe6e7d56feb with fgi_status is completed

One thing is very strange. I could not find this info in the log when the auto clean was successfully executed such as this [ironic-conductor.log](https://github.com/metal3-io/baremetal-operator/files/7114141/ironic-conductor.log)

**Comment by sshukun** [comment]
@dtantsur thank you for the explanation.
> 2) cleaning is over before the job is actually finished.

After investigation, I think the job is actually finished normally before cleaning is over. 
This `NoneType` error and the log you see is because iRMC RAID implementation filters the nodes by the wrong field.

To check the progress of running RAID config, iRMC filters the nodes by `raid_config` which will not be cleared after RAID configuration complete. Therefore the periodic check will always check the nodes who are in `clean wait` state and have value in `raid_config` and then resume clean even during auto clean. 
https://opendev.org/openstack/ironic/src/branch/master/ironic/drivers/modules/irmc/raid.py#L433-L434

I think we should change iRMC to use `driver_internal_info` for filtering instead of `raid_config` and clear the raid config in `driver_internal_info` after RAID configuration completed, just like other implementations.

**Comment by dtantsur** [comment]
> Therefore the periodic check will always check the nodes who are in clean wait state and have value in raid_config and then resume clean even during auto clean

Yes, this is possible as well.

**Comment by zaneb** [comment]
/remove-lifecycle stale
@hs0210 @Hellcatlk @sshukun do we have an update on fixing the issues with the iRMC driver in ironic that Dmitry identified above?

**Comment by fenggw-fnst** [comment]
@zaneb 
Sorry for late reply, and sorry for that the status of the issues Dmitry identified above are not tracked well here.
These issues should have been resolved by now. Please refer to:
https://storyboard.openstack.org/#!/story/2009206
https://storyboard.openstack.org/#!/story/2009231
https://review.opendev.org/c/openstack/ironic/+/809022
https://review.opendev.org/c/openstack/ironic/+/809023

**Comment by Rozzii** [comment]
Based on the info provided by @fenggw-fnst we can close this.
/close
